import { Calibre } from './page';
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={Calibre.variable}>{children}</body>
    </html>
  );
}
